orbs:
  anchore: anchore/anchore-engine@1.6.0

version: 2.1
jobs:
  lint:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    
    working_directory: ~/repo
    
    steps:
      - checkout
    
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
    
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x /bin/hadolint
      - save_cache:
           paths:
             - ./venv
           key: v1-dependencies-{{ checksum "requirements.txt" }}
    
          # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
  local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build image
          command: 'docker build -t "test/housepricemlapi:latest" .'
      - anchore/analyze_local_image:
          dockerfile_path: ./Dockerfile
          image_name: 'test/housepricemlapi:latest'
          policy_bundle_file_path: .circleci/.anchore/policy_bundle.json
          policy_failure: true
          timeout: '500'
      - anchore/parse_reports
      - store_artifacts:
          path: anchore-reports

  build_image:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    
    working_directory: ~/repo
    
    steps:
      - checkout
    
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
    
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x /bin/hadolint
      - save_cache:
           paths:
             - ./venv
           key: v1-dependencies-{{ checksum "requirements.txt" }}
    
          # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
   

workflows:
  default:
    jobs:
      - lint
      - local_image_scan
      - build_image

